/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SonandoConmigoRouteImport } from './routes/sonando-conmigo'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuenoIndexRouteImport } from './routes/sueno.index'
import { Route as MercadoIndexRouteImport } from './routes/mercado.index'
import { Route as ComunidadIndexRouteImport } from './routes/comunidad.index'
import { Route as SuenoProgrammerRouteImport } from './routes/sueno.programmer'
import { Route as SuenoDeseosRouteImport } from './routes/sueno.deseos'
import { Route as SuenoChatRouteImport } from './routes/sueno.chat'
import { Route as SuenoIdRouteImport } from './routes/sueno.$id'
import { Route as MercadoSymbolRouteImport } from './routes/mercado.$symbol'
import { Route as ComunidadMapaRouteImport } from './routes/comunidad.mapa'
import { Route as ComunidadComponerRouteImport } from './routes/comunidad.componer'
import { Route as SuenoArchivoIndexRouteImport } from './routes/sueno.archivo.index'
import { Route as SuenoArchivoIdRouteImport } from './routes/sueno.archivo.$id'
import { Route as ComunidadUUsernameRouteImport } from './routes/comunidad.u.$username'
import { Route as ComunidadLugarSlugRouteImport } from './routes/comunidad.lugar.$slug'

const SonandoConmigoRoute = SonandoConmigoRouteImport.update({
  id: '/sonando-conmigo',
  path: '/sonando-conmigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuenoIndexRoute = SuenoIndexRouteImport.update({
  id: '/sueno/',
  path: '/sueno/',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoIndexRoute = MercadoIndexRouteImport.update({
  id: '/mercado/',
  path: '/mercado/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadIndexRoute = ComunidadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComunidadRoute,
} as any)
const SuenoProgrammerRoute = SuenoProgrammerRouteImport.update({
  id: '/sueno/programmer',
  path: '/sueno/programmer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuenoDeseosRoute = SuenoDeseosRouteImport.update({
  id: '/sueno/deseos',
  path: '/sueno/deseos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuenoChatRoute = SuenoChatRouteImport.update({
  id: '/sueno/chat',
  path: '/sueno/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SuenoIdRoute = SuenoIdRouteImport.update({
  id: '/sueno/$id',
  path: '/sueno/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoSymbolRoute = MercadoSymbolRouteImport.update({
  id: '/mercado/$symbol',
  path: '/mercado/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadMapaRoute = ComunidadMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => ComunidadRoute,
} as any)
const ComunidadComponerRoute = ComunidadComponerRouteImport.update({
  id: '/componer',
  path: '/componer',
  getParentRoute: () => ComunidadRoute,
} as any)
const SuenoArchivoIndexRoute = SuenoArchivoIndexRouteImport.update({
  id: '/sueno/archivo/',
  path: '/sueno/archivo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuenoArchivoIdRoute = SuenoArchivoIdRouteImport.update({
  id: '/sueno/archivo/$id',
  path: '/sueno/archivo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadUUsernameRoute = ComunidadUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => ComunidadRoute,
} as any)
const ComunidadLugarSlugRoute = ComunidadLugarSlugRouteImport.update({
  id: '/lugar/$slug',
  path: '/lugar/$slug',
  getParentRoute: () => ComunidadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidad': typeof ComunidadRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/scanner': typeof ScannerRoute
  '/sonando-conmigo': typeof SonandoConmigoRoute
  '/comunidad/componer': typeof ComunidadComponerRoute
  '/comunidad/mapa': typeof ComunidadMapaRoute
  '/mercado/$symbol': typeof MercadoSymbolRoute
  '/sueno/$id': typeof SuenoIdRoute
  '/sueno/chat': typeof SuenoChatRoute
  '/sueno/deseos': typeof SuenoDeseosRoute
  '/sueno/programmer': typeof SuenoProgrammerRoute
  '/comunidad/': typeof ComunidadIndexRoute
  '/mercado/': typeof MercadoIndexRoute
  '/sueno/': typeof SuenoIndexRoute
  '/comunidad/lugar/$slug': typeof ComunidadLugarSlugRoute
  '/comunidad/u/$username': typeof ComunidadUUsernameRoute
  '/sueno/archivo/$id': typeof SuenoArchivoIdRoute
  '/sueno/archivo/': typeof SuenoArchivoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/scanner': typeof ScannerRoute
  '/sonando-conmigo': typeof SonandoConmigoRoute
  '/comunidad/componer': typeof ComunidadComponerRoute
  '/comunidad/mapa': typeof ComunidadMapaRoute
  '/mercado/$symbol': typeof MercadoSymbolRoute
  '/sueno/$id': typeof SuenoIdRoute
  '/sueno/chat': typeof SuenoChatRoute
  '/sueno/deseos': typeof SuenoDeseosRoute
  '/sueno/programmer': typeof SuenoProgrammerRoute
  '/comunidad': typeof ComunidadIndexRoute
  '/mercado': typeof MercadoIndexRoute
  '/sueno': typeof SuenoIndexRoute
  '/comunidad/lugar/$slug': typeof ComunidadLugarSlugRoute
  '/comunidad/u/$username': typeof ComunidadUUsernameRoute
  '/sueno/archivo/$id': typeof SuenoArchivoIdRoute
  '/sueno/archivo': typeof SuenoArchivoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidad': typeof ComunidadRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/scanner': typeof ScannerRoute
  '/sonando-conmigo': typeof SonandoConmigoRoute
  '/comunidad/componer': typeof ComunidadComponerRoute
  '/comunidad/mapa': typeof ComunidadMapaRoute
  '/mercado/$symbol': typeof MercadoSymbolRoute
  '/sueno/$id': typeof SuenoIdRoute
  '/sueno/chat': typeof SuenoChatRoute
  '/sueno/deseos': typeof SuenoDeseosRoute
  '/sueno/programmer': typeof SuenoProgrammerRoute
  '/comunidad/': typeof ComunidadIndexRoute
  '/mercado/': typeof MercadoIndexRoute
  '/sueno/': typeof SuenoIndexRoute
  '/comunidad/lugar/$slug': typeof ComunidadLugarSlugRoute
  '/comunidad/u/$username': typeof ComunidadUUsernameRoute
  '/sueno/archivo/$id': typeof SuenoArchivoIdRoute
  '/sueno/archivo/': typeof SuenoArchivoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidad'
    | '/perfil'
    | '/scanner'
    | '/sonando-conmigo'
    | '/comunidad/componer'
    | '/comunidad/mapa'
    | '/mercado/$symbol'
    | '/sueno/$id'
    | '/sueno/chat'
    | '/sueno/deseos'
    | '/sueno/programmer'
    | '/comunidad/'
    | '/mercado/'
    | '/sueno/'
    | '/comunidad/lugar/$slug'
    | '/comunidad/u/$username'
    | '/sueno/archivo/$id'
    | '/sueno/archivo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/perfil'
    | '/scanner'
    | '/sonando-conmigo'
    | '/comunidad/componer'
    | '/comunidad/mapa'
    | '/mercado/$symbol'
    | '/sueno/$id'
    | '/sueno/chat'
    | '/sueno/deseos'
    | '/sueno/programmer'
    | '/comunidad'
    | '/mercado'
    | '/sueno'
    | '/comunidad/lugar/$slug'
    | '/comunidad/u/$username'
    | '/sueno/archivo/$id'
    | '/sueno/archivo'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comunidad'
    | '/perfil'
    | '/scanner'
    | '/sonando-conmigo'
    | '/comunidad/componer'
    | '/comunidad/mapa'
    | '/mercado/$symbol'
    | '/sueno/$id'
    | '/sueno/chat'
    | '/sueno/deseos'
    | '/sueno/programmer'
    | '/comunidad/'
    | '/mercado/'
    | '/sueno/'
    | '/comunidad/lugar/$slug'
    | '/comunidad/u/$username'
    | '/sueno/archivo/$id'
    | '/sueno/archivo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComunidadRoute: typeof ComunidadRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  ScannerRoute: typeof ScannerRoute
  SonandoConmigoRoute: typeof SonandoConmigoRoute
  MercadoSymbolRoute: typeof MercadoSymbolRoute
  SuenoIdRoute: typeof SuenoIdRoute
  SuenoChatRoute: typeof SuenoChatRoute
  SuenoDeseosRoute: typeof SuenoDeseosRoute
  SuenoProgrammerRoute: typeof SuenoProgrammerRoute
  MercadoIndexRoute: typeof MercadoIndexRoute
  SuenoIndexRoute: typeof SuenoIndexRoute
  SuenoArchivoIdRoute: typeof SuenoArchivoIdRoute
  SuenoArchivoIndexRoute: typeof SuenoArchivoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sonando-conmigo': {
      id: '/sonando-conmigo'
      path: '/sonando-conmigo'
      fullPath: '/sonando-conmigo'
      preLoaderRoute: typeof SonandoConmigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sueno/': {
      id: '/sueno/'
      path: '/sueno'
      fullPath: '/sueno/'
      preLoaderRoute: typeof SuenoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado/': {
      id: '/mercado/'
      path: '/mercado'
      fullPath: '/mercado/'
      preLoaderRoute: typeof MercadoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad/': {
      id: '/comunidad/'
      path: '/'
      fullPath: '/comunidad/'
      preLoaderRoute: typeof ComunidadIndexRouteImport
      parentRoute: typeof ComunidadRoute
    }
    '/sueno/programmer': {
      id: '/sueno/programmer'
      path: '/sueno/programmer'
      fullPath: '/sueno/programmer'
      preLoaderRoute: typeof SuenoProgrammerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sueno/deseos': {
      id: '/sueno/deseos'
      path: '/sueno/deseos'
      fullPath: '/sueno/deseos'
      preLoaderRoute: typeof SuenoDeseosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sueno/chat': {
      id: '/sueno/chat'
      path: '/sueno/chat'
      fullPath: '/sueno/chat'
      preLoaderRoute: typeof SuenoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sueno/$id': {
      id: '/sueno/$id'
      path: '/sueno/$id'
      fullPath: '/sueno/$id'
      preLoaderRoute: typeof SuenoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado/$symbol': {
      id: '/mercado/$symbol'
      path: '/mercado/$symbol'
      fullPath: '/mercado/$symbol'
      preLoaderRoute: typeof MercadoSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad/mapa': {
      id: '/comunidad/mapa'
      path: '/mapa'
      fullPath: '/comunidad/mapa'
      preLoaderRoute: typeof ComunidadMapaRouteImport
      parentRoute: typeof ComunidadRoute
    }
    '/comunidad/componer': {
      id: '/comunidad/componer'
      path: '/componer'
      fullPath: '/comunidad/componer'
      preLoaderRoute: typeof ComunidadComponerRouteImport
      parentRoute: typeof ComunidadRoute
    }
    '/sueno/archivo/': {
      id: '/sueno/archivo/'
      path: '/sueno/archivo'
      fullPath: '/sueno/archivo/'
      preLoaderRoute: typeof SuenoArchivoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sueno/archivo/$id': {
      id: '/sueno/archivo/$id'
      path: '/sueno/archivo/$id'
      fullPath: '/sueno/archivo/$id'
      preLoaderRoute: typeof SuenoArchivoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad/u/$username': {
      id: '/comunidad/u/$username'
      path: '/u/$username'
      fullPath: '/comunidad/u/$username'
      preLoaderRoute: typeof ComunidadUUsernameRouteImport
      parentRoute: typeof ComunidadRoute
    }
    '/comunidad/lugar/$slug': {
      id: '/comunidad/lugar/$slug'
      path: '/lugar/$slug'
      fullPath: '/comunidad/lugar/$slug'
      preLoaderRoute: typeof ComunidadLugarSlugRouteImport
      parentRoute: typeof ComunidadRoute
    }
  }
}

interface ComunidadRouteChildren {
  ComunidadComponerRoute: typeof ComunidadComponerRoute
  ComunidadMapaRoute: typeof ComunidadMapaRoute
  ComunidadIndexRoute: typeof ComunidadIndexRoute
  ComunidadLugarSlugRoute: typeof ComunidadLugarSlugRoute
  ComunidadUUsernameRoute: typeof ComunidadUUsernameRoute
}

const ComunidadRouteChildren: ComunidadRouteChildren = {
  ComunidadComponerRoute: ComunidadComponerRoute,
  ComunidadMapaRoute: ComunidadMapaRoute,
  ComunidadIndexRoute: ComunidadIndexRoute,
  ComunidadLugarSlugRoute: ComunidadLugarSlugRoute,
  ComunidadUUsernameRoute: ComunidadUUsernameRoute,
}

const ComunidadRouteWithChildren = ComunidadRoute._addFileChildren(
  ComunidadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComunidadRoute: ComunidadRouteWithChildren,
  PerfilRoute: PerfilRoute,
  ScannerRoute: ScannerRoute,
  SonandoConmigoRoute: SonandoConmigoRoute,
  MercadoSymbolRoute: MercadoSymbolRoute,
  SuenoIdRoute: SuenoIdRoute,
  SuenoChatRoute: SuenoChatRoute,
  SuenoDeseosRoute: SuenoDeseosRoute,
  SuenoProgrammerRoute: SuenoProgrammerRoute,
  MercadoIndexRoute: MercadoIndexRoute,
  SuenoIndexRoute: SuenoIndexRoute,
  SuenoArchivoIdRoute: SuenoArchivoIdRoute,
  SuenoArchivoIndexRoute: SuenoArchivoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
